package iti.Misk.model.newentity;
// Generated Apr 10, 2025, 10:36:31 PM by Hibernate Tools 6.0.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Useraddress generated by hbm2java
 */
@Entity
@Table(name="useraddress"
    ,catalog="misk"
)
public class Useraddress  implements java.io.Serializable {


     private int addressId;
     private User user;
     private String state;
     private String city;
     private String street;
     private Long departmentNumber;
     private Set<Order> orders = new HashSet<Order>(0);

    public Useraddress() {
    }

	
    public Useraddress(int addressId, String state, String city, String street) {
        this.addressId = addressId;
        this.state = state;
        this.city = city;
        this.street = street;
    }
    public Useraddress(int addressId, User user, String state, String city, String street, Long departmentNumber, Set<Order> orders) {
       this.addressId = addressId;
       this.user = user;
       this.state = state;
       this.city = city;
       this.street = street;
       this.departmentNumber = departmentNumber;
       this.orders = orders;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="address_id", unique=true, nullable=false)
    public int getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(int addressId) {
        this.addressId = addressId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="state", nullable=false, length=14)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="city", nullable=false, length=255)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="street", nullable=false, length=65535)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="department_number")
    public Long getDepartmentNumber() {
        return this.departmentNumber;
    }
    
    public void setDepartmentNumber(Long departmentNumber) {
        this.departmentNumber = departmentNumber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="useraddress")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


